local_backend: true

backend:
    name: "github"
    repo: friendsofdonegal/website-v2
    branch: main
    base_url: https://friends-of-donegal-2024.netlify.app
    automatic_deployments: false

media_folder: "apps/web/public/images"
public_folder: "/public/images"

collections:
  - name: "board-members"
    label: "Board Members"
    folder: "apps/web/src/content/board-members"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Image", name: "imageUrl", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: programs
    label: Programs
    folder: apps/web/src/content/programs
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Homepage Index", name: "homepageIndex", widget: "number", required: false }
      - label: "Donate Key"
        name: "paypalDonateKey"
        widget: "select"
        options: ["FriendsOfDonegal", "DonegalPowerPacks", "DonegalCommunityGarden", "GettingAhead",]
